version: "3"
services:
  database:
    image: "mongo"
    container_name: "mern-example"
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass

    ports:
      - "27017-27019:27017-27019"
